services:
  postgres:
    container_name: postgres-sql-brc
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_community
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-net
    restart: unless-stopped

  keycloak:
    container_name: keycloak-brc
    image: quay.io/keycloak/keycloak
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    networks:
      - spring-net
    command:
      - "start-dev"

networks:
  spring-net:
    driver: bridge

volumes:
  postgres:
    driver: local